Trait {
	#name : #TBlSteppedLayoutMarkVisitor,
	#category : #'Bloc-Layout-Stepped'
}

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutAllToBottomMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutAllToLeftMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutAllToRightMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutAllToUpMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutBottomLeftMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutBottomRightMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutMark: aMark [
	
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutUndefinedMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutUpLeftMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]

{ #category : #visiting }
TBlSteppedLayoutMarkVisitor >> visitSteppedLayoutUpRightMark: aMark [
	^ self visitSteppedLayoutMark: aMark
]
